// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      // apiKey: 'AIzaSyDUP6X1di-ekI5O0DuxozZw_D51odtHtkQ',
      // appId: '',
      // messagingSenderId: '247551785039',
      // projectId: 'chatclone-dd871',
      // authDomain: 'chatclone-10a0d.firebaseapp.com',
      // storageBucket: 'chatclone-10a0d.appspot.com',
      apiKey: "AIzaSyDUP6X1di-ekI5O0DuxozZw_D51odtHtkQ",
      authDomain: "chatclone-dd871.firebaseapp.com",
      projectId: "chatclone-dd871",
      storageBucket: "chatclone-dd871.appspot.com",
      messagingSenderId: "247551785039",
      appId: "1:247551785039:web:0257570718463485e3923a");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUP6X1di-ekI5O0DuxozZw_D51odtHtkQ',
    appId: '1:247551785039:android:fc5b1c9858636227e3923a',
    messagingSenderId: '247551785039',
    projectId: 'chatclone-dd871',
    storageBucket: 'chatclone-dd871.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUP6X1di-ekI5O0DuxozZw_D51odtHtkQ',
    appId: '1:247551785039:ios:97413c2331ca8118e3923a',
    messagingSenderId: '247551785039',
    projectId: 'chatclone-dd871',
    storageBucket: 'chatclone-dd871.appspot.com',
    iosClientId:
        '165248862031-g7jt2ijris41uoeg08iibadcdulkpta5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvAbAmshzbmr5fzEFBwwuojvWRzLSpQMg',
    appId: '1:165248862031:ios:01834024a1eaa858fd273a',
    messagingSenderId: '165248862031',
    projectId: 'chatclone-10a0d',
    storageBucket: 'chatclone-10a0d.appspot.com',
    iosClientId:
        '165248862031-g7jt2ijris41uoeg08iibadcdulkpta5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatclone',
  );
}



///flutterfire configure --project=chatclone-dd871